name: Bare Run on various PHP versions

on:
    push:
        branches:
            - main

jobs:
    bare_run:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

        steps:
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}

            # nest to directory to avoid using current repository
            -   run: mkdir nested-directory

            # allow plugin installing
            -   run: composer config --no-plugins allow-plugins.cweagans/composer-patches true
                working-directory: nested-directory

            -   run: composer require symplify/vendor-patches --dev
                working-directory: nested-directory

            -   run: vendor/bin/vendor-patches list --ansi
                working-directory: nested-directory
